# Generated by Django 2.2.3 on 2019-09-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lang',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='name_fa',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
